FROM ubuntu:16.04
MAINTAINER Zach LaCelle <zlacelle@mitre.org>

USER root
SHELL ["/bin/bash", "-c"]

# These configurations are copied so that dpkg-reconfigure doesn't hang
COPY --chown=root:root ["docker_container_extras/etc_default_keyboard", "/etc/default/keyboard"]
COPY --chown=root:root ["docker_container_extras/etc_default_console-setup", "/etc/default/console-setup"]


# Configure proxy settings
ENV http_proxy http://gatekeeper.mitre.org:80
ENV HTTP_PROXY http://gatekeeper.mitre.org:80
ENV https_proxy http://gatekeeper.mitre.org:80
ENV HTTPS_PROXY http://gatekeeper.mitre.org:80
ENV ftp_proxy http://gatekeeper.mitre.org:80
ENV FTP_PROXY http://gatekeeper.mitre.org:80
ENV proxy http://gatekeeper.mitre.org:80
ENV PROXY http://gatekeeper.mitre.org:80

# Update and install base Ubuntu
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y ubuntu-server

# Building
RUN apt-get install -y apt-utils ca-certificates git unzip wget build-essential \
  make cmake gcc gnupg clang sudo apt-transport-https curl gnupg-agent \
  software-properties-common

# After installing git, setup git proxy
RUN git config --global http.proxy http://gatekeeper.mitre.org:80

# Also after installing, set up ROS repo
# ROS
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
RUN curl -sSL 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xC1CF6E31E6BADE8868B172B4F42ED6FBAB17C654' | sudo apt-key add -
RUN apt-get update

# Fix sudoers env keep
COPY ["docker_container_extras/etc_sudoers_envkeepfix.sh", "/tmp/"]
RUN /tmp/etc_sudoers_envkeepfix.sh
RUN rm /tmp/etc_sudoers_envkeepfix.sh

# Get MITRE certs and update certificates
COPY ["docker_container_extras/MITRE BA ROOT.crt", "/usr/local/share/ca-certificates/MITRE BA ROOT.crt"]
COPY ["docker_container_extras/MITRE BA NPE CA-3.crt", "/usr/local/share/ca-certificates/MITRE BA NPE CA-3.crt"]
COPY ["docker_container_extras/MITRE BA NPE CA-4.crt", "/usr/local/share/ca-certificates/MITRE BA NPE CA-4.crt"]
RUN ln -f -s /usr/local/share/ca-certificates/MITRE\ BA\ ROOT.crt /etc/ssl/certs/MITRE-BA-ROOT.pem
RUN ln -f -s /usr/local/share/ca-certificates/MITRE\ BA\ NPE\ CA-3.crt /etc/ssl/certs/MITRE-BA-NPE-CA3.pem
RUN ln -f -s /usr/local/share/ca-certificates/MITRE\ BA\ NPE\ CA-4.crt /etc/ssl/certs/MITRE-BA-NPE-CA4.pem
RUN cat /usr/local/share/ca-certificates/MITRE\ BA\ ROOT.crt /usr/local/share/ca-certificates/MITRE\ BA\ NPE\ CA-3.crt /usr/local/share/ca-certificates/MITRE\ BA\ NPE\ CA-4.crt | tee /etc/ssl/certs/MITRE_COMBO.pem
RUN update-ca-certificates

# Add a build user
RUN useradd -rm -d /home/gitlab -s /bin/bash -g root -G sudo -u 1000 gitlab

# Setup DART repos
RUN wget -qO - http://dart-repos.mitre.org/public.asc | sudo apt-key add -
RUN echo "deb http://dart-repos.mitre.org/ppa `lsb_release -sc` main" > /etc/apt/sources.list.d/dart-repos.list
RUN apt-get update

# Install python
RUN apt-get install -y --no-install-recommends python-minimal python-pip
RUN pip install --no-cache-dir --upgrade pip setuptools

# DART development setup
RUN apt-get install -y dart-dev
USER gitlab
RUN sudo rosdep init
USER root

# Set ROS update
RUN echo "source /opt/ros/kinetic/setup.bash" >> ~/.bashrc
